### ISSUE TITLE
Some typo errors

### ISSUE THREAD

**Issue by katesroad** [FUSIONFoundation/web3-fusion-extend#5]
#### Expected behavior
At here:  https://fusionapi.readthedocs.io/en/latest/getting-started.html#usage
Bellow the [Community](https://fusionapi.readthedocs.io/en/latest/getting-started.html#community), we expect both the Gitter and Forum link point to Fusion's forum and Gitter.

#### Actual behavior
The URL: https://fusionapi.readthedocs.io/en/latest/getting-started.html#usage
Bellow the Community title, the Gitter and Forum point to Ethruem forum and Gitter link.

**Comment by JoeyKhd** [comment]
Hi Kate, 

There will be a freshly rewritten API documentation coming out soon. Be on the lookout!

Joey
