### ISSUE TITLE
Could not send Asset

### ISSUE THREAD

**Issue by sangduongvan** [FUSIONFoundation/web3-fusion-extend#6]
I try to do very simple case is sending FSN using privatekey.

Here is my code in nodejs
```javascript

const Web3 = require("web3");
const web3FusionExtend = require('web3-fusion-extend')


let _FSNASSETID = '0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff';
let _NETWORK = "wss://testnetpublicgateway1.fusionnetwork.io:10001"
let _CHAINID = 46688;

let provider = new Web3.providers.WebsocketProvider(_NETWORK);
let web3 = new Web3(provider);
web3 = web3FusionExtend.extend(web3);

async function test() {    
    let payload = {
        from: '0xC8367BAb4d0e61A53fdf3D637C5e8D32c8ad9E7f',
        to: '0x08685bdD88c57518FD315Fc904aD1A27d8C1b1a0',
        value: "1",
        asset: _FSNASSETID
    }
    console.log(payload);
    await web3.fsntx.buildSendAssetTx(payload).then((tx) => {
        const account = web3.eth.accounts.privateKeyToAccount('0xeaafe8a2221a1d023fe55fd9df3f6784ae91746863e279b9f7a286722cbc6d22');
        console.log(tx);
        tx.from = account.address.toLowerCase();
        tx.chainId = parseInt(_CHAINID);
        
        return web3.fsn.signAndTransmit(tx, account.signTransaction)
            .then(txHash => {
                this.addOutput(`Transaction Hash : ${txHash}`);
            });
    });
}

test();

```

But I always get error: 

(node:740) UnhandledPromiseRejectionWarning: Error: Incompatible EIP155-based V 0 and chain id 0xb660. See the second parameter of the Transaction constructor to set the chain id.
    at Transaction._validateV (/Data/projects/MPL/Fusion/testweb3/node_modules/ethereumjs-tx/dist/transaction.js:310:19)
    at new Transaction (/Data/projects/MPL/Fusion/testweb3/node_modules/ethereumjs-tx/dist/transaction.js:138:14)
    at signed (/Data/projects/MPL/Fusion/testweb3/node_modules/web3-eth-accounts/src/index.js:224:25)
    at /Data/projects/MPL/Fusion/testweb3/node_modules/web3-eth-accounts/src/index.js:272:16
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

Env: 
node: v8.16.0
npm: 6.9.0
OS: Mac High Sierra

package.json file:
```
{
  "name": "testweb3",
  "version": "1.0.0",
  "description": "",
  "main": "test.js",
  "dependencies": {
    "web3": "^1.2.2",
    "web3-fusion-extend": "^1.0.0-beta.36"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

```

**Comment by JoeyKhd** [comment]
Please, downgrade web3 to 1.2.1 thank you.

**Comment by sangduongvan** [comment]
> Please, downgrade web3 to 1.2.1 thank you.

Ok thank you, it works with web3 1.2.1
